# change prefix from 'Ctrl-b' to 'Ctrl-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Status bar on top
set -g status-position top

# Windows start at 1
set -g base-index 1

# Panes start at 1
setw -g pane-base-index 1

# Ensure window index updates when one is closed
set -g renumber-windows on

# Stop tmux from automatically renaming windows
set-option -g allow-rename off

# Enable extended keys (CSI u)
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

# Enable allow-passthrough for image.nvim
set -g allow-passthrough on

# Fix screen rendering issues
set -sg escape-time 0
set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Improve rendering for external programs
set -g focus-events on
set -g monitor-activity off
set -g visual-activity off

# Fix alternate screen and terminal reset issues
set -g alternate-screen on
setw -g xterm-keys on

# Enable OSC52 clipboard support for Linux terminals
set -s set-clipboard on

# Vi mode for copy mode
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel